### ISSUE TITLE
zoom level 19 and 20

### ISSUE THREAD

**Issue by quite** [karlwettin/carto-style-hydda#2]
As I mentioned I'm still getting the gaps between tiles, depending on browser model and moon phase I suppose... But, zoom level 19 and 20 are blank! This is not what the readme promises! ;-D  

This has the maxzoom 20: https://quite--fruktkartan.netlify.com/

**Comment by karlwettin** [comment]
I don't know what up there with your app, but using [our own test app](http://tile.openstreetmap.se/#20/56.88082/14.81317) we're getting z20 and never see any white lines.

Debugging really quick with Chrome it seems as yours isn't even attempting to request the z19 and z20 tiles? Could it be something crazy like a very old Leaflet that doesn't know there are maps that can zoom that great and thus don't have support for evaluation what tiles it should request?

**Comment by quite** [comment]
Ah! Actually yes, it seems the ready vue2leaflet component that I used was indeed pulling in and using an older leaflet (peerdependencies huh). Using leaflet straight up in vue/vuetify does allow for zoom 20! Thanks!

**Comment by quite** [comment]
In the end, vue2leaflet was actually using the latest Leaflet. I didn't understand `PeerDependencies`. So there is something else with my vue app...

**Comment by quite** [comment]
For the record, the issue was tha `maxZoom: 20` had to be passed to the vue `l-tile-layer` component, not to `l-map`.
